export const MOVIES_FETCH = {
  FETCH_MOVIES_DATA: "FETCH_MOVIES_DATA",
  FETCHED_DATA: "FETCHED_DATA",
  RECEIVE_ERROR: "RECEIVE_ERROR",
}

export const  SET_MOVIES_FILTER = "SET_MOVIES_FILTER";

export const MOVIE_FETCH = {
  OPEN_MOVIE_MODAL: "OPEN_MOVIE_MODAL",
  FETCH_MOVIE_DATA: "FETCH_MOVIE_DATA",
  CLOSE_MOVIE_MODAL: "CLOSE_MOVIE_MODAL",
  FETCH_CREDITS: "FETCH_CREDITS",
  SHOW_ERROR: "SHOW_ERROR"
}

export const FAVORITE = {
  ADD_MOVIE: "ADD_MOVIE",
  GO_TO_FAVORITES: "GO_TO_FAVORITES",
  CLOSE_FAVORITE: "CLOSE_FAVORITE",
  REMOVE_FROM_FAVORITE: "REMOVE_FROM_FAVORITE"
}

export const PAGINATION = {
  GO_TO_NEXT_PAGE: "GO_TO_NEXT_PAGE",
  GO_BACK_TO_PAGE: "GO_BACK_TO_PAGE",
  GO_TO_CHOSEN_PAGE: "GO_TO_CHOSEN_PAGE",
  SET_TOTAL_PAGES: "SET_TOTAL_PAGES",
  RESET_PAGE: "RESET_PAGE"
} 