export const SEARCH_FETCH = {
  FETCH_SEARCH_DATA: "FETCH_SEARCH_DATA",
  FETCHED_DATA: "FETCHED_DATA",
  RECEIVE_ERROR: "RECEIVE_ERROR"
}

export const MOVIE_FETCH = {
  OPEN_MOVIE_MODAL: "OPEN_MOVIE_MODAL",
  FETCH_MOVIE_DATA: "FETCH_MOVIE_DATA",
  CLOSE_MOVIE_MODAL: "CLOSE_MOVIE_MODAL"
}